### **1. Import library**

In [1]:
import torch
import numpy as np

### 2. Tensor **張量的基本寫法**

In [4]:
torch.tensor([[1, 2], [3, 4], [5, 6]]) # 建立一個張量

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64) # 可使用 dtype 來設定數據類型

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [7]:
torch.zeros([2, 2]) # 建立全為 0 的張量

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones([2, 2]) # 建立全為 1 的張量

tensor([[1., 1.],
        [1., 1.]])

In [5]:
torch.eye(3) # 建立單位矩陣

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### 3. **torch**.device 設定分配的設備

In [10]:
if torch.cuda.is_available():
   cuda0 = torch.device('cuda:0')
   t1 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, device=cuda0)

In [13]:
cuda0 = torch.device('cuda', 0) # 設定分配的設備

In [12]:
cuda1 = torch.device('cuda', 1) # 使用第二個GPU

In [11]:
cpu = torch.device('cpu') # 使用CPU