### **1. Import library**

In [ ]:
import torch
import numpy as np

### 2. Tensor **張量的基本寫法**

In [ ]:
torch.tensor([[1, 2], [3, 4], [5, 6]]) # 建立一個張量

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64) # 可使用 dtype 來設定數據類型

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [ ]:
torch.zeros([2, 2]) # 建立全為 0 的張量

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones([2, 2]) # 建立全為 1 的張量

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.eye(3) # 建立單位矩陣

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### 3. **torch**.device 設定分配的設備

In [ ]:
if torch.cuda.is_available():
   cuda0 = torch.device('cuda:0')
   t1 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, device=cuda0)

In [ ]:
cuda0 = torch.device('cuda', 0) # 設定分配的設備

In [ ]:
cuda1 = torch.device('cuda', 1) # 使用第二個GPU

In [ ]:
cpu = torch.device('cpu') # 使用CPU

### **4. Autograd 以計算梯度**
requires_grad：是否需要追蹤該 Tensor 以計算梯度

In [ ]:
# 建立 Tensor 並設定 requires_grad 為 True
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, requires_grad=True)
# 建立隨機數值的 Tensor 並設定 requires_grad 為 True
torch.randn(2, 3, requires_grad=True)

backward()：計算梯度

In [ ]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)
# 計算梯度
c.backward()
# 查看 x 的梯度值
print(x.grad)

在 with torch.no_grad()的影響下。。。

In [ ]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
print("set x requires_grad:", x.requires_grad)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)
print("org c requires_grad:", c.requires_grad)
# 設定 no_grad()
with torch.no_grad():
  d = x * y
print("set d requires_grad:", d.requires_grad)

### **5. Datasets, DataLoader**

**5.1. torch.utils.data.Datasets**
*   資料集的抽象類別，可以採用自己定義或是官方公開數據集


In [ ]:
import torch
import torchvision
from torch.utils.data import Dataset
class Dataset(object):
    def __init__(self):
      # 定義初始化參數
      # 讀取資料集路徑
    def __getitem__(self, index):
      # 讀取每次迭代的資料集中第 idx  資料
      # 進行前處理 (torchvision.Transform 等)
      return # 資料和 label
    def __len__(self):
      # 計算資料集總共數量
      return # 資料集總數

5.2. torch.utils.data.DataLoader

*   定義每一次迭代要取樣多少資料量、是否要打亂數據 (shuffle)、使用單/多執行緒 (thread) 等等



\begin{array}{|c|c|c|c|}\hline
No.&parameter&usage&prop.\\ \hline
1&\text{dataset}&\text{from which to load data}&\text{-}\\
2&\text{batch_size}&\text{how many samples per batch to load}&\text{int; 1}\\
3&\text{shuffle}&\text{data reshuffled at every epoch}&\text{bool; False}\\
4&\text{sampler}&\text{draw samples from the dataset}&\text{Can be any Iterable with __len__ implemented}\\
5&\text{batch_sampler}&\text{like sampler, but returns a batch of indices at a time}&\text{-}\\
6&\text{num_workers}&\text{how many subprocesses to use for data loading}&\text{int; 0 means that the data will be loaded in the main process; 0}\\
7&\text{collate_fn}&\text{merges a list of samples to form a mini-batch of Tensor}&\text{Used when using batched loading from a map-style dataset}\\
8&\text{pin_memory}&\text{If True, the data loader will copy Tensors into device/CUDA pinned memory before returning them}&\text{bool}\\
9&\text{drop_last}&\text{drop the last incomplete batch}&\text{bool; (if the dataset size is not divisible by the batch size)}\\
10&\text{timeout}&\text{ if positive, the timeout value for collecting a batch from workers}&\text{0; non-negative}\\
11&\text{worker_init_fn}&\text{}&\text{}\\
12&\text{multiprocessing_context}&\text{}&\text{}\\
13&\text{generator}&\text{}&\text{}\\
14&\text{prefetch_factor}&\text{}&\text{}\\
15&\text{persistent_workers }&\text{}&\text{}\\
16&\text{pin_memory_device }&\text{}&\text{}\\ \hline
\end{array}

In [ ]:
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from torchvision import transforms
train_transform = transforms.Compose([
                  transforms.Resize((256, 256)),
                  transforms.ToTensor(),
                  transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
# 使用 torchvision.datasets.ImageFolder 讀取貓狗資料
image_folder = ImageFolder("./data/dog_cat_data", transform=train_transform, target_transform=None)
# 建立 DataLoader，shuffle 為 True 表示會將資料進行打亂
data_loader = DataLoader(dataset = image_folder, batch_size= 100, shuffle= True, num_workers= 2)
# 列印數據
for batch_idx, (data, target) in enumerate(data_loader):
     print("data:", data)
     print("label:", target)

### **6. Network**

* 建立神經網路模型需繼承 torch.nn.Module

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self): #建構神經網路裡的各個層
        super(network_name, self).__init__()
        # network layer
    def forward(self, x):
        # forward propagation
        return output

當創建完模型後，使用模型輸入資料進行預測時，就會直接執行
forward()，不需再另外調用。

In [ ]:
model = Model()
output = model(data)

### **7. Loss Functions、Optimizer**

In [ ]:
import torch.nn as nn
import torch.optim as optim
criterion = nn.CrossEntropyLoss()                                 # nn for Loss Functions
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)  # optim for optimizer

### **8. Training**

In [ ]:
# 訓練格式
for epoch in range(epoch_size):
    train_loss = 0.0
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)

        if CUDA:
            data, target = data.cuda(), target.cuda()

        # clear gradient
        optimizer.zero_grad()

        # Forward propagation
        output = model(data)
        loss = criterion(output, target)

        # Calculate gradients
        loss.backward()

        # Update parameters
        optimizer.step()

        predicted = torch.max(output.data, 1)[1]
        train_loss += loss.item()

### **9. Save, Load Model**

In [ ]:
#只儲存模型的權重
torch.save(model.state_dict(), 'model_weights.pth')
# 讀取權重
model.load_state_dict(torch.load('model_weights.pth'))
#完整儲存整個模型
torch.save(model, 'model.pth')
#load 整個模型
model = torch.load('model.pth')

### **10. TensorBoard**

*   由視覺化的方式來觀察與紀錄訓練結果的好用工具，可依照個人需求設定要記錄的項目




In [ ]:
from torch.utils.tensorboard import SummaryWriter
log_dir = "./log_dir/"
writer = SummaryWriter(log_dir)
# 寫入資料
writer.add_scalar(tag, scalar_value)
writer.add_histogram(tag, values)
writer.add_image(tag, img_tensor)

# 開啟 tensorboard
# tensorboard --logdir="./log_dir"