<a href="https://colab.research.google.com/github/lum33/ML-Tutorial/blob/main/My_Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **1. Import library**

In [ ]:
import torch
import numpy as np

### 2. Tensor **張量的基本寫法**

In [ ]:
torch.tensor([[1, 2], [3, 4], [5, 6]]) # 建立一個張量

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64) # 可使用 dtype 來設定數據類型

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [ ]:
torch.zeros([2, 2]) # 建立全為 0 的張量

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones([2, 2]) # 建立全為 1 的張量

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.eye(3) # 建立單位矩陣

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### 3. **torch**.device 設定分配的設備

In [ ]:
if torch.cuda.is_available():
   cuda0 = torch.device('cuda:0')
   t1 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, device=cuda0)

In [ ]:
cuda0 = torch.device('cuda', 0) # 設定分配的設備

In [ ]:
cuda1 = torch.device('cuda', 1) # 使用第二個GPU

In [ ]:
cpu = torch.device('cpu') # 使用CPU

### **4. Autograd 以計算梯度**
requires_grad：是否需要追蹤該 Tensor 以計算梯度

In [ ]:
# 建立 Tensor 並設定 requires_grad 為 True
torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float64, requires_grad=True)
# 建立隨機數值的 Tensor 並設定 requires_grad 為 True
torch.randn(2, 3, requires_grad=True)

backward()：計算梯度

In [ ]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)
# 計算梯度
c.backward()
# 查看 x 的梯度值
print(x.grad)

在 with torch.no_grad()的影響下。。。

In [ ]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
print("set x requires_grad:", x.requires_grad)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)
print("org c requires_grad:", c.requires_grad)
# 設定 no_grad()
with torch.no_grad():
  d = x * y
print("set d requires_grad:", d.requires_grad)

### **5. Datasets, DataLoader**

**5.1. torch.utils.data.Datasets**
*   資料集的抽象類別，可以採用自己定義或是官方公開數據集


In [ ]:
import torch
import torchvision
from torch.utils.data import Dataset
class Dataset(object):
    def __init__(self):
      # 定義初始化參數
      # 讀取資料集路徑
    def __getitem__(self, index):
      # 讀取每次迭代的資料集中第 idx  資料
      # 進行前處理 (torchvision.Transform 等)
      return # 資料和 label
    def __len__(self):
      # 計算資料集總共數量
      return # 資料集總數

5.2. torch.utils.data.DataLoader

*   義每一次迭代要取樣多少資料量、是否要打亂數據 (shuffle)、使用單/多執行緒 (thread) 等等



In [ ]:
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
from torchvision import transforms
train_transform = transforms.Compose([
                  transforms.Resize((256, 256)),
                  transforms.ToTensor(),
                  transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
# 使用 torchvision.datasets.ImageFolder 讀取貓狗資料
image_folder = ImageFolder("./data/dog_cat_data", transform=train_transform, target_transform=None)
# 建立 DataLoader，shuffle 為 True 表示會將資料進行打亂
data_loader = DataLoader(dataset = image_folder, batch_size= 100, shuffle= True, num_workers= 2)
# 列印數據
for batch_idx, (data, target) in enumerate(data_loader):
     print("data:", data)
     print("label:", target)